"""user profiles vk

Revision ID: e1b635257996
Revises: 
Create Date: 2026-06-29 12:56:19.401976
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1b635257996'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_group_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_vk_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('brand_color', sa.String(length=9), nullable=False),
    sa.Column('brand_logo_url', sa.String(length=500), nullable=True),
    sa.Column('payment_provider', sa.String(length=20), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('guest_reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('guest_expire_enabled', sa.Boolean(), nullable=False),
    sa.Column('guest_expire_minutes', sa.Integer(), nullable=False),
    sa.Column('publish_notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('cancel_lock_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_chat_id'),
    sa.UniqueConstraint('vk_group_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_group_name')
    )
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tg_user_id', name='uq_membership_unique')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_tg_user_id'), 'memberships', ['tg_user_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_sent'), 'outbox', ['sent'], unique=False)
    op.create_index(op.f('ix_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', 'user_id', name='uq_subscriber_unique')
    )
    op.create_index(op.f('ix_subscribers_tenant_id'), 'subscribers', ['tenant_id'], unique=False)
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('guest_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('guests_expired', sa.Boolean(), nullable=False),
    sa.Column('created_by_platform', sa.String(length=8), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_group_id'), 'trainings', ['group_id'], unique=False)
    op.create_index(op.f('ix_trainings_tenant_id'), 'trainings', ['tenant_id'], unique=False)
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'training_id', 'platform', 'user_id', name='uq_signup_unique')
    )
    op.create_index(op.f('ix_signups_tenant_id'), 'signups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_signups_training_id'), 'signups', ['training_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('signup_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_training_id'), 'payments', ['training_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_training_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_signups_training_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_tenant_id'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_trainings_tenant_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_group_id'), table_name='trainings')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_subscribers_tenant_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_outbox_tenant_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_sent'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_memberships_tg_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('tenants')
    # ### end Alembic commands ###
